// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package flags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/i"

func AseanUnion(props ...i.Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<path fill=\"#0039a6\" d=\"M0 24h30V0H0z\"></path> <path fill=\"#fff\" d=\"M15 18a6 6 0 1 0 0-12 6 6 0 0 0 0 12\"></path> <path fill=\"#ed2939\" d=\"M15 17.72a5.72 5.72 0 1 0 0-11.44 5.72 5.72 0 0 0 0 11.44\"></path> <path fill=\"#f9e300\" d=\"M13.46 12c-.99-.59-1.46-1.78-1.46-3h.45v.04c0 .42.08 1.86 1.17 2.96a4.3 4.3 0 0 0-1.17 2.96V15H12c0-1.22.47-2.41 1.46-3\"></path> <path fill=\"#f9e300\" d=\"M12.61 9.04V9h.46v.05c0 .42.08 1.81.88 2.95a5.5 5.5 0 0 0-.88 2.95V15h-.46v-.04c0-.4.1-1.85 1.18-2.96a4.5 4.5 0 0 1-1.18-2.96\"></path> <path fill=\"#f9e300\" d=\"m14.11 12-.03-.04a5.4 5.4 0 0 1-.85-2.9V9h.46v.07c0 .44.05 1.77.58 2.93a8 8 0 0 0-.58 2.93V15h-.46v-.05c0-.41.05-1.67.85-2.91\"></path> <path fill=\"#f9e300\" d=\"M14.43 12a8 8 0 0 1-.58-3h.46v.14c0 .5.03 1.72.28 2.86a14 14 0 0 0-.28 3h-.46v-.07c0-.43.05-1.8.58-2.92\"></path> <path fill=\"#f9e300\" d=\"M14.76 12v-.02a14 14 0 0 1-.29-2.84V9h.45v6h-.45v-.14c0-.49.03-1.72.29-2.84\"></path> <path fill=\"#f9e300\" d=\"M16.54 12c.99-.59 1.46-1.78 1.46-3h-.45v.04A4.3 4.3 0 0 1 16.38 12a4.3 4.3 0 0 1 1.17 2.96V15H18c0-1.22-.47-2.41-1.46-3\"></path> <path fill=\"#f9e300\" d=\"M17.39 9.04V9h-.46v.05c0 .42-.08 1.81-.88 2.95.8 1.14.88 2.53.88 2.95V15h.46v-.04c0-.4-.1-1.85-1.18-2.96a4.5 4.5 0 0 0 1.18-2.96\"></path> <path fill=\"#f9e300\" d=\"m15.89 12 .03-.04c.8-1.24.85-2.5.85-2.9V9h-.46v.07c0 .44-.05 1.77-.58 2.93a8 8 0 0 1 .58 2.93V15h.46v-.05c0-.41-.05-1.67-.85-2.91\"></path> <path fill=\"#f9e300\" d=\"M15.57 12a8 8 0 0 0 .58-3h-.46v.14c0 .5-.03 1.72-.28 2.86.25 1.14.28 2.37.28 2.86V15h.46v-.07c0-.43-.05-1.8-.58-2.92\"></path> <path fill=\"#f9e300\" d=\"M15.24 12v-.02c.26-1.12.29-2.35.29-2.84V9h-.45v6h.45v-.14c0-.49-.03-1.72-.29-2.84\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = i.FlagIcon("0 0 30 24", props...).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
