// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package flags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/i"

func Cambodia(props ...i.Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<path fill=\"#0f299c\" d=\"M0 24V0h30v24z\"></path> <path fill=\"#ce2c2d\" d=\"M0 4h30v16H0z\"></path> <path fill=\"#fff\" d=\"M22 15.56h-.35v-.68h-.35v-.57h-.35v-.44h-.2v-.33c-1.18.12-.04-2.08-.27-2.71q-.14 0-.2.1c.06-.15-.1-.6-.19-.24h-.18v-.48c-.45.42-.1.08-.26-.33 0 .06-.09.2-.12.18.07-.16.16-.28.04-.5-.15.46.04-.05-.1-.26l-.07.2c.05-.8-.77-.8-.72 0l-.07-.2c-.14.2.04.72-.1.25-.12.23-.04.35.03.51-.03.01-.11-.12-.12-.18-.15.41.2.75-.26.33v.85h-.22c.02-.1-.19-.1-.16 0h-1.3v-.78c-.2.08-.19.18-.18.3-.23.1-.27-.31-.05-.3v-.32c-.04 0-.16 0-.26.16v-.08c-.14-.01-.14.12-.14.37h-.04c-.1-.35.3-.5.1-.85-.34.54.26-.4-.03-.57-.27.73.08-.26-.15-.4-.17.66.05-.21-.1-.27-.23.43.07-.1-.1-.21-.16.28-.06-.11-.04-.19h-.06l.02-.17h-.08l.02-.14h-.14l.01-.14h-.12c.03-.29-.32-.29-.3 0h-.12l.01.14h-.13l.02.14h-.08l.02.17h-.06c0 .07.1.47-.05.19-.16.1.14.64-.1.2-.14.1.09.89-.1.28-.23.14.13 1.13-.14.4-.3.17.3 1.12-.03.57-.21.34.2.5.1.85h-.02c0-.27 0-.38-.15-.37v.08c-.1-.15-.22-.15-.26-.16v.32c.21-.02.19.4-.04.3 0-.12 0-.22-.2-.3v.78h-1.3c.04-.1-.17-.1-.15 0h-.22v-.85c-.45.42-.1.09-.26-.33 0 .07-.09.2-.12.18.07-.16.15-.28.03-.5-.14.46.05-.05-.1-.26 0 .05-.06.2-.07.2.05-.8-.77-.8-.71 0l-.07-.2c-.15.2.04.72-.1.25-.13.23-.04.35.03.51-.03.01-.11-.11-.12-.18-.15.42.2.75-.26.33v.48H9.9c-.1-.36-.25.09-.19.25q-.06-.1-.2-.11c-.23.63.92 2.82-.27 2.7v.34h-.2v.44H8.7v.58h-.35v.67H8v.73h14z\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = i.FlagIcon("0 0 30 24", props...).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
