// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package flags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/i"

func CommonwealthOfIndependentStates(props ...i.Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<path fill=\"#0073cf\" d=\"M0 24h30V0H0z\"></path> <path fill=\"#fff\" d=\"M11.73 18.4v-5.7a11 11 0 0 1-3.55-1.83.47.47 0 1 1 .64-.67 8 8 0 0 0 3.47 2.34v5.85zm.75 0v-5.98a8 8 0 0 1-3.94-2.86.56.56 0 1 1 .96-.55 6 6 0 0 0 3.54 3.3v6.09zm.75 0v-6.23a5.8 5.8 0 0 1-3.9-4.35.8.8 0 1 1 1.58-.08 4.1 4.1 0 0 0 2.88 4.34v6.32zm.74 0v-6.46a3.92 3.92 0 0 1-1.6-6.7.93.93 0 1 1 1.13 1.48 2.8 2.8 0 0 0 1.03 5.13v6.55z\"></path> <path fill=\"#fff\" d=\"M18.27 18.4v-5.7a11 11 0 0 0 3.55-1.83.47.47 0 1 0-.64-.67 8 8 0 0 1-3.47 2.34v5.85zm-.75 0v-5.98a8 8 0 0 0 3.94-2.86.56.56 0 1 0-.96-.55 6 6 0 0 1-3.54 3.3v6.09zm-.75 0v-6.23a5.8 5.8 0 0 0 3.9-4.35.8.8 0 1 0-1.58-.08 4.1 4.1 0 0 1-2.88 4.34v6.32zm-.74 0v-6.46a3.92 3.92 0 0 0 1.6-6.7.93.93 0 1 0-1.13 1.48 2.8 2.8 0 0 1-1.03 5.13v6.55z\"></path> <path fill=\"#fff\" d=\"M14.72 11.88q.28.01.56 0v6.52h-.56z\"></path> <path fill=\"#fecb00\" d=\"M15 10.21a1.12 1.12 0 1 0 0-2.24 1.12 1.12 0 0 0 0 2.24\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = i.FlagIcon("0 0 30 24", props...).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
