// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package flags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/i"

func Ethiopia(props ...i.Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<path fill=\"#f7df4b\" d=\"M0 8h30v8H0z\"></path> <path fill=\"#3c883a\" d=\"M30 8H0V0h30z\"></path> <path fill=\"#c92d25\" d=\"M30 24H0v-8h30z\"></path> <path fill=\"#1e44aa\" d=\"M15 6a6 6 0 1 0 0 12 6 6 0 0 0 0-12\"></path> <path fill=\"#f6dd4c\" d=\"m15 6.9-.22.7.92 2.83h-1.23l-.14.42h3.94l.58-.42h-2.7z\"></path> <path fill=\"#f6dd4c\" d=\"m16.29 10.05 1.62-2.23.17.12-1.62 2.23zm3.55.38h-.72l-2.4 1.75-.39-1.17h-.44l1.21 3.74.58.43-.83-2.58z\"></path> <path fill=\"#f6dd4c\" d=\"m19.8 13.67-2.61-.85.06-.2 2.63.85zM18 16.12l-.23-.69-2.41-1.75 1-.72-.15-.42-3.18 2.31-.22.69 2.19-1.6z\"></path> <path fill=\"#f6dd4c\" d=\"M14.9 14.33h.2v2.76h-.2zM12 16.12l.6-.43.91-2.83 1 .73.36-.27-3.19-2.3h-.72l2.2 1.58z\"></path> <path fill=\"#f6dd4c\" d=\"m10.2 13.67-.07-.2 2.62-.85.06.2zm-.04-3.24.58.42h2.98l-.38 1.17.36.26 1.22-3.74-.23-.69-.83 2.58z\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = i.FlagIcon("0 0 30 24", props...).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
