// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package flags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/i"

func HeardAndMcdonaldIslands(props ...i.Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<path fill=\"#071b65\" d=\"M0 0h30v24H0z\"></path> <path fill=\"#fff\" d=\"m5.3 19.4-1.12 1.05.11-1.53-1.52-.24 1.27-.86-.76-1.34 1.46.45.57-1.43.56 1.43 1.47-.45-.76 1.34 1.26.86-1.52.24.12 1.53zM22.8 4.22l-.74.68.08-1-1-.15.83-.57-.5-.87.96.3.37-.94.37.93.96-.3-.5.88.83.57-1 .15.08 1zm-3.7 5.54-.73.68.07-1-1-.15.84-.57-.5-.87.96.3.37-.94.37.93.96-.3-.5.88.83.57-1 .15.08 1zm8.32-1.85-.74.69.07-1-1-.16.84-.57-.5-.87.96.3.37-.94.37.94.96-.3-.5.87.82.57-.99.15.07 1zM22.8 20.83l-.74.68.08-1-1-.16.83-.56-.5-.88.96.3.37-.94.37.94.96-.3-.5.88.83.56-1 .16.08 1zm2.82-10.68.27.55.6.1-.44.42.1.6-.53-.28-.55.28.1-.6-.43-.43.6-.09z\"></path> <path fill=\"#fff\" d=\"M5.5 9.77V12h4V9.77L12.54 12H15v-1.24L11.24 8H15V4h-2.74L15 2V0h-1.44L9.5 2.98V0h-4v2.8L1.75 0H0v1.9L2.99 4H0v4h3.76L0 10.76V12h2.46z\"></path> <path fill=\"#b92932\" d=\"m0 1 4.09 3h1.36L0 0zm0 11 5.45-4v1l-4.09 3z\"></path> <path fill=\"#b92932\" d=\"M8.5 12h-2V7H0V5h6.5V0h2v5H15v2H8.5z\"></path> <path fill=\"#b92932\" d=\"M15 11.67 10 8v1l4.1 3h.9zM15 0h-.25L9.3 4h1.37L15 .82z\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = i.FlagIcon("0 0 30 24", props...).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
