// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package flags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/i"

func Iran(props ...i.Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<path fill=\"#fff\" d=\"M0 8h30v8H0z\"></path> <path fill=\"#4d9e4a\" d=\"M30 8H0V0h30z\"></path> <path fill=\"#c92a1d\" d=\"M30 24H0v-8h30zM17.06 12.8a3.1 3.1 0 0 0-.93-3.33 3.43 3.43 0 0 1-.83 4.69l.1-2.56V9.59q-.25-.12-.4-.35-.15.23-.4.35v2.01l.1 2.56a3.43 3.43 0 0 1-.82-4.7 3.13 3.13 0 0 0 .58 5.15 3 3 0 0 1-1.34.2q.8.25 1.61.09v.1l.27.37.27-.36v-.11a3 3 0 0 0 1.61-.09 4 4 0 0 1-1.34-.2 3 3 0 0 0 1.52-1.8\"></path> <path fill=\"#c92a1d\" d=\"M18.08 10.63a2.6 2.6 0 0 0-1.63-1.23 3.43 3.43 0 0 1 .68 4.8l-.01.01a2.6 2.6 0 0 0 .96-3.58M13.55 9.4a2.62 2.62 0 0 0-.67 4.81 3.43 3.43 0 0 1 .67-4.8m.76-.18A.5.5 0 0 0 15 9.1a.5.5 0 0 0 .86-.47.47.47 0 0 1-.86.15.47.47 0 0 1-.86-.15.5.5 0 0 0 .17.59\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = i.FlagIcon("0 0 30 24", props...).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
