// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package flags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/i"

func SouthAmericanUnion(props ...i.Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<path fill=\"#2e42a5\" d=\"M0 24h30V0H0z\"></path> <path fill=\"#f7fcff\" d=\"M4.12 6.41c-.31-.23.04-.7.37-.47q.32.22 1.2.74 1.49.86 3.33 1.66a27 27 0 0 0 11.45 2.4 8 8 0 0 0 2.27-.34q-.18-.43-.55-.93c-.2-.27.14-.6.42-.42a5 5 0 0 1 1.02.94c1-.66 1.06-1.7-.17-3.4-.2-.26.14-.6.42-.4q.11.06.33.24.38.3.71.66c1.03 1.1 1.42 2.28.74 3.4a2.7 2.7 0 0 1-1.35 1.12q0 .63-.45 1.19-.16.24-.68.55-.37.2-.85.34 0 .52-.38.97-.14.2-.57.46-.6.36-1.49.41-.06.26-.24.48-.11.15-.41.33a2.4 2.4 0 0 1-1.18.3h-.1q-.95.05-2.39-.19a12.6 12.6 0 0 1-5.34-2.3c-.31-.23.04-.7.36-.47l.51.31q.64.36 1.41.7c1.57.68 3.21 1.07 4.86 1.02a3 3 0 0 0 1.02-.17 18.3 18.3 0 0 1-10.36-3.69c-.31-.24.04-.7.37-.48q.2.16.77.48.95.55 2.14 1.07a17.5 17.5 0 0 0 7.35 1.54h.02l-.16-.26a.27.27 0 0 1 .07-.41q-.93-.09-2-.27a23 23 0 0 1-9.74-4.19c-.31-.23.04-.7.37-.47q.26.18.96.59c.77.44 1.66.9 2.63 1.3a22 22 0 0 0 9.06 1.9q.4.01 1.01-.08-.1-.22-.27-.46A28.3 28.3 0 0 1 4.12 6.4m15.3 7.79.14.17q.84-.14 1.24-.5-.8.02-1.81-.05.19.13.43.38m2.26-1.5c.6-.19 1.16-.5 1.4-1-.5.3-1.15.3-2.12.3.14.1.41.25.72.7M7.06 5.53c-.31-.24.04-.7.37-.48q.23.16.86.53 1.05.6 2.36 1.18a19 19 0 0 0 8.15 1.7c.36 0 .9-.04 1.42-.18 1.37-.37 1.75-1.12.64-2.64-.2-.27.15-.6.43-.42q.31.2.76.67c.75.81 1.04 1.69.53 2.52a2 2 0 0 1-.79.73 4 4 0 0 1-2.03.47 20.7 20.7 0 0 1-12.7-4.08m8.49 13.07c-.07.41-.63.46-1.32.32-.68-.13-1.18-.38-1.11-.77.06-.41.62-.46 1.31-.32.69.13 1.18.38 1.12.77\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = i.FlagIcon("0 0 30 24", props...).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
