// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package flags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/i"

func SouthKorea(props ...i.Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<path fill=\"#fff\" d=\"M0 0h30v24H0z\"></path> <path fill=\"#000\" d=\"M5.57 8.44 8.1 4.67l.63.41L6.2 8.86zm.95.63 2.51-3.78.63.42L7.14 9.5zm.94.62 2.51-3.77.63.42-2.52 3.77zm15.19 7.18 1.15-1.73.63.42-1.15 1.73zm-1.36 2.04 1.15-1.72.63.42-1.16 1.72zm.41-2.67 1.16-1.73.62.42-1.15 1.73zm-1.36 2.05 1.15-1.73.63.42-1.15 1.73zm.42-2.67 1.15-1.73.63.42-1.15 1.72zm-1.36 2.04 1.15-1.73.63.42-1.15 1.72z\"></path> <path fill=\"#be3b3e\" d=\"M11.23 9.49a4.53 4.53 0 1 1 7.54 5.03z\"></path> <path fill=\"#1c449c\" d=\"M11.23 9.49a4.53 4.53 0 1 0 7.54 5.03A2.27 2.27 0 0 0 15 12z\"></path> <path fill=\"#be3b3e\" d=\"M13.11 8.48a2.27 2.27 0 1 0 0 4.53 2.27 2.27 0 0 0 0-4.53\"></path> <path fill=\"#000\" d=\"m5.57 15.56.63-.42 2.51 3.77-.62.43zm1.89-1.25.63-.42 2.51 3.77-.63.42zm12.88-8.6.63-.42 2.52 3.78-.63.42zM6.51 14.93l.63-.42 1.15 1.73-.62.42zm1.37 2.05.62-.42 1.16 1.73-.63.41zM19.4 6.34l.63-.42 1.15 1.73-.63.42zm1.36 2.05.63-.42 1.15 1.72-.62.42zm.53-3.3.62-.42 1.16 1.72-.63.42zm1.36 2.04.63-.42 1.15 1.73-.63.42z\"></path> <path fill=\"#fff\" d=\"M26 1H4a3 3 0 0 0-3 3v1a3 3 0 0 1 3-3h22a3 3 0 0 1 3 3V4a3 3 0 0 0-3-3\" opacity=\".2\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = i.FlagIcon("0 0 30 24", props...).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
